In [11]:
# Deliverable One. Open a new Jupyter Notebook and load CSV file into the Jupyter Notebook.

# Task 1: Download the BUS336_Signature_Term_Project_Starbucks_Beverage_Menu CSV file from either the 
# Projects/Assignments folder in Blackboard or the GitHub account provided. 
# Save the CSV file in your C:\Users\YOUR COMPUTER NAME FOLDER.

In [12]:
# Task 2: Import pandas as pd to work with a package that can process dataframes.
# ENTER CODE BELOW THIS LINE.
import pandas as pd

# Import the BUS336_Signature_Term_Project_Starbucks_Beverage_Menu.csv file using the pandas package.
# ENTER CODE BELOW THIS LINE.
file_path = 'C:/Users/rober/BUS336_Signature_Term_Project_Starbucks_Beverage_Menu.csv'
df = pd.read_csv(file_path)

In [13]:
# Task 3: Rename the Jupyter Notebook from Untitled to the following name convention: 
# LastName_FirstName_BUS 336_Signature_Term_Project. 

# The file will be stored in the your C:\Users\YOUR COMPUTER NAME FOLDER.

In [14]:
# Delivarable Two. Explore rows with all blank values and remove them.

# Task 1: Using the isnull and sum functions, check the total NaN entries for all columns in the dataframe.
# ENTER CODE BELOW THIS LINE.
nan_counts = df.isnull().sum()
nan_counts

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [15]:
# Task 2: View the dataframe with the head function.
# ENTER CODE BELOW THIS LINE.
df.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

In [16]:
# Task 3: Remove the row with all blank entries.
# The how='all' will drop all rows with only NaN values. 
# ENTER CODE BELOW THIS LINE.
df = df.dropna(how='all')
df.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

In [17]:
# Task 4: Validate that the blank row(s) have been removed.
# Use the isnull and sum functions to validate that df2 has only one column remains with an NaN.
# ENTER CODE BELOW THIS LINE.
nan_counts_after_cleaning = df.isnull().sum()
nan_counts_after_cleaning

Product_Name           0
Size                   0
Milk                   0
Whip                   0
Serving_Size_ml        0
Calories               0
Total_Fat_g            0
Saturated_Fat_g        1
Trans_Fat_g            0
Cholesterol_mg         0
Sodium_mg              0
Carbohydrates_g        0
Dietary_Fiber_g        0
Sugar_g                0
Protein_g              0
Vitamin_A_%DV          0
Vitamin_C_%DV          0
Calcium_%DV            0
Iron_%DV               0
Caffiene_milligrams    0
dtype: int64

In [18]:
# Deliverable Three. Explore the data types and correct any errors.

# Task One: Using the dtypes function, check the data types.
# ENTER CODE BELOW THIS LINE.
df.dtypes

Product_Name            object
Size                    object
Milk                    object
Whip                    object
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                 object
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [19]:
# Task 2: Look for column with the incorrect data type, understand why it is incorrect, 
# and change it to the correct data type.

# In the dataframe, the Sugar_mg column has an incorrect string entry when it should be numeric. 
# A 0 value was entered as "zero". This will not result in a NaN, but Python will recognize this as a string. 
# We need to convert the string “zero” to an actual numerical 0. As a demonstration, we use the current dataframe that we are
# working with and use the index numbers to isolate the row and column. The iloc function helps us isolate that the entry
# zero is in the second row, 14th column (index positions 1 and 13). We set that cell value to the number 0 and it will change the "zero" to 0.
# Run the code and look compare the Sugar_g column in df1 to df and see how the "zero" turns into a 0.
df.iloc[1,13] = 0
df.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

In [20]:
# Change Suger_g type to float.
# ENTER CODE BELOW THIS LINE.
df['Sugar_g'] = df['Sugar_g'].astype(float)

In [21]:
# Validate that the Sugar_g variable has been changed to a float.
# ENTER CODE BELOW THIS LINE.
df.dtypes

Product_Name            object
Size                    object
Milk                    object
Whip                    object
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                float64
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [22]:
# Deliverable Four. Explore the NaN values and remove the row with any NaN values.

# Task 1: Using the info function, check for one NaN value.
# If the Non-Null Count has multiple “1204 non-null” entries, but one has a “1203 non-null” entry, 
# then that column still has a NaN value.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   object
 1   Size                 1204 non-null   object
 2   Milk                 1204 non-null   object
 3   Whip                 1204 non-null   object
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.5+ KB

In [23]:
# Task 2: Assign a new dataframe df2 and remove the row with the NaN entry from the Saturated_Fat_g column in df1.
# Drop any remaining rows that have an NaN.
# ENTER CODE BELOW THIS LINE.
df2 = df.copy()
df2 = df2.dropna(subset=['Saturated_Fat_g'])
df2 = df2.dropna()
df2.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [24]:
# Task 3: Validate that it has been corrected.
# Run the info function.
# ENTER CODE BELOW THIS LINE.
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   object
 1   Size                 1203 non-null   object
 2   Milk                 1203 non-null   object
 3   Whip                 1203 non-null   object
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.4+ KB

In [25]:
# Deliverable Five: Change a column name.

# Task 1: Assign the dataframe to df3 and using the rename function, change the Caffiene_milligrams column header 
# from the df2 dataframe to Caffiene_mg.
# ENTER CODE BELOW THIS LINE.
df3 = df2.rename(columns={'Caffiene_milligrams': 'Caffiene_mg'})

In [26]:
# Task 2: Validate that it has been corrected.
# ENTER CODE BELOW THIS LINE.
df3.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [27]:
# Deliverable Six: Describe the continuous and categorical data.

# Task 1: Using dataframe df3, use the describe() function to describe the continuous variables.

# Continuous variables obtain the measures of central tendency, such as the mean and median,
# as well as variance information such as standard deviations. 
# ENTER CODE BELOW THIS LINE.
df3.describe()

,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
count,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000
mean,464.700748,230.825436,6.365254,3.980050,0.122111,15.551122,142.817124,37.589360,0.857024,34.950125,5.993682,10.197839,3.014131,18.013300,7.768911,81.996675
std,159.715633,132.048992,5.892705,3.988006,0.151344,17.964969,89.905690,22.467672,1.506892,21.638249,4.839338,8.686005,14.124793,15.594855,13.303877,76.483998
min,236.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,354.000000,140.000000,1.500000,0.300000,0.000000,0.000000,75.000000,20.000000,0.000000,19.000000,2.000000,2.000000,0.000000,2.000000,0.000000,20.000000
50%,473.000000,220.000000,5.000000,3.000000,0.000000,5.000000,135.000000,35.000000,0.000000,33.000000,5.000000,10.000000,0.000000,15.000000,0.000000,75.000000
75%,591.000000,310.000000,10.000000,7.000000,0.200000,30.000000,200.000000,53.000000,1.000000,48.000000,9.000000,15.000000,0.000000,25.000000,10.000000,130.000000
max,887.000000,640.000000,28.000000,20.000000,0.500000,75.000000,370.000000,96.000000,8.000000,89.000000,25.000000,50.000000,240.000000,90.000000,90.000000,475.000000

In [28]:
# Task 2: Using dataframe df3, use the describe() function to describe the categorical variables.

# Categorical variable to get the count of rows, unique count of categories, top category, and freq of top category.
df3.describe(include='object')

               Product_Name    Size    Milk     Whip
count                  1203    1203    1203     1203
unique                   94       7       6        2
top     White Hot Chocolate  Grande  Nonfat  No Whip
freq                     50     345     240      910

In [29]:
# Task 3: Analyze, interpret, and write about the continuous and categorical variables.

# There are a many observations to note about the continuous variables that your client maybe interested to hear. 
# Here are just a few continuous variable observations. Students can note different ones.
# The minimum size for any drink is 236 ml, which is about 8 ounces. The maximum is 887 ml, which is about 30 ounces.
# Could there be opportunities to serve smaller or larger drinks? Why did Starbucks choose these drink size ranges?
# Every nutritional measure has a minimum zero count. What could that indicate?
# There drinks tend to have more Cholestoral then less. Look at the 0% to 50% percentage compared to the 75% to 100%.

#using the continuous variable we can observe a lot about the Starbucks menu. first, the minimum sizing is 236 ml and the   
# maximum is 887 ml. The data show that the mean of the sizing is 465 ml which is almost half the largest size and double the smallest.
# . 


# There are many observations to note about the categorical variables that your client maybe interested to hear. 
# Here are just a few categorical variable observations. Students can note different ones.
# There are 1,203 different drink combinations. Approximately 94 are unique product names. 
# What resources does it take to train its employees to know the products?
# White Hot Chocolate is the Product Name that is repeated most often. Why? 
# Grande seems to be the most popular size.
# Customers appear to prefer Non-fat milk and do not prefer Whip cream for drinks that have that option.
# There are six different types of Milk options. Nowadays, the Milk options on the market far exceed six. 
# Is there an opportunity here?
# There are seven different sizes for drinks. Is this too many, too little, or just the right amount?

# Using the categorial variables we can see what the most popular flavors, sizes, and options Starbucks offers. 
# THis information can be useful for helping design a new menu for a new coffee spot. We can see that Starbucks offers 7 different 
# sizes of cups. Since we already know their max, min, and, mean sizes we can base the new coffee spots based on those and offer three sizes
# that utilize the information we were able to gather. We also know the most popular flavor Starbucks offers since it appears most often in their menu.
# This flavor would make a great jumping-off point for the new coffee spot.

In [30]:
# Deliverable Seven: Write the dataframe to a CSV file, save it, and verify it as a CSV file.

# Task 1: Using the to_csv function, write dataframe df3 to a new df4.CSV file.
# ENTER CODE BELOW THIS LINE.
df3.to_csv('df4.csv', index=False)

In [31]:
# Task 2: 
# You do not have to make an entries to code anything for this task. Just check your file to make sure that df4 is saved.

In [32]:
# Task 3: Assign a new dataframe and load the CSV file back into the Jupyter Notebook using the pandas package. 
# ENTER CODE BELOW THIS LINE.
df4 = pd.read_csv('df4.csv')

In [37]:
# Task 4: Open the newly created CSV file in the Jupyter Notebook.
# ENTER CODE BELOW THIS LINE.
df4.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [34]:
# Deliverable Eight: Upload file into your GitHub Account.

# Share your work with others! You do not need to do anything else inside this file. Anyone who has the file can replicate
# the work that you have done. They can modify it at will.
# Now you will be able to explain to anyone what you did and how you did it with a clean trail. 
# Try duplicating that feat in Excel!

# Task #1: Open your GitHub account and upload the newly created df4.csv file.
# Task #2: Validate that it has been uploaded and can be opened by emailing it to yourself and  instructor.

In [35]:
# Deliverable Nine: Make a short video explaining deliverables one through nine.

# Follow the instruction in the Step-by-Step guide to submit it.

# Task #1: Rehearse, record, and present a video presentation.
# Task #2: Upload the video presentation.

In [36]:
# Deliverable Ten: Write a reflection below.

Start typing your reflection below this paragraph. You do not have to include a hash tag to begin the line as you did in Delivarabe Six. 
Just start typing and make sure that you put in line breaks when you get close to the right margin like you see here.
Try to hit the run button for this code block. You will get an SyntaxError message. Don't worry about it. I can still read 
your reflection. I just want you to see the difference if you type a narrative with or without a #.

# ENTER Reflection BELOW THIS LINE.

it was very interesting implementing the lessons from data camp into a real-world project. Putting all of those lessons together allowed
me to grasp the concepts of loading, cleaning, converting, and describing. I found it really interesting being able to load a file and 
manipulate it to gather the information that was important to me. Instead of going into the Excel file and doing all of that work,
it was much easier to utilize pandas.

SyntaxError: unterminated string literal (detected at line 5) (435654564.py, line 5)